# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'qwios' do
pod "SwiftyJSON", ">= 2.1.3"
pod 'Socket.IO-Client-Swift', '~> 1.3.2'
end

target 'qwiosTests' do

end

